### ISSUE TITLE
"Module not found" error when building project on Digital Ocean App Platform

### ISSUE THREAD

**Issue by mitchellcliftonbarton** [ivodolenc/nuxt-gsap-module#19] opened 2021-08-12 19:50 UTC
I'm trying to deploy a Nuxt app to the Digital Ocean App Platform, and whenever i run the build, it gives me this error:

```
ERROR in ./.nuxt/gsapModule.js
Module not found: Error: Can't resolve 'gsap' in '/workspace/.nuxt'
@ ./.nuxt/gsapModule.js 14:0-28 21:4-8 25:4-8 29:4-8 33:4-8 36:22-26 43:2-6
@ ./.nuxt/index.js
@ ./.nuxt/client.js
@ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js
```

I think I have things set up correctly, here is my nuxt.config.js file:

```
buildModules: [
    'nuxt-gsap-module',
 ],

...

gsap: {
    extraPlugins: {
      draggable: true
    },
  },
```

Any idea on why this might be happening?

**Comment by ivodolenc** [comment] 2021-08-13 12:04
Unfortunately, it's difficult to say where the problem is with the info you provided.

The first thing that comes to mind is try deleting `node_modules`, `dist`, `.nuxt` directories and then reinstall everything (also try searching for similar issues on google, there is certainly some information that could help you).

> I think I have things set up correctly, here is my nuxt.config.js file:

Yep, that's fine 👍

```js
// nuxt.config.js

export default {
  buildModules: ['nuxt-gsap-module'],

  gsap: {
    extraPlugins: {
      draggable: true
    }
  }
}
```

**Comment by mitchellcliftonbarton** [comment] 2021-08-13 20:22
Thanks! I didnt have much info to go off of, but your suggestion led me in the right direction. Turns out what was happening had nothing to do with nuxt-gsap-module, but I updated core-js from version 3.15.1 to 3.16.1 and that seemed to do the trick.

**Comment by ivodolenc** [comment] 2021-08-16 08:19
Awesome, I'm glad it worked for you. Closing this as resolved.

**Closed by ivodolenc** 2021-08-16 08:19 UTC
